/*
============================
Database restore using IMPDP
http://ss64.com/ora/impdp.html
============================
*/

--1. Create an Oracle database

--2. Connect as SYS

--3. Grant public permissions for Oracle geodatabase

GRANT EXECUTE ON dbms_pipe TO public;
GRANT EXECUTE ON dbms_lock TO public;
GRANT EXECUTE ON dbms_lob TO public;
GRANT EXECUTE ON dbms_utility TO public;
GRANT EXECUTE ON dbms_sql TO public;
GRANT EXECUTE ON utl_raw TO public;


--4. Create a tablespace for each new user schema

CREATE TABLESPACE PROCESS DATAFILE '/home/oracle/orcl/oradata/drew/PROCESS.dbf'
SIZE 100M AUTOEXTEND ON NEXT 51200K MAXSIZE UNLIMITED EXTENT MANAGEMENT
LOCAL UNIFORM SIZE 320K LOGGING ONLINE SEGMENT SPACE MANAGEMENT MANUAL;
CREATE TABLESPACE SDE DATAFILE '/home/oracle/orcl/oradata/drew/SDE.dbf'
SIZE 100M AUTOEXTEND ON NEXT 51200K MAXSIZE UNLIMITED EXTENT MANAGEMENT
LOCAL UNIFORM SIZE 320K LOGGING ONLINE SEGMENT SPACE MANAGEMENT MANUAL;
CREATE TABLESPACE SDEALLEDITS_DT DATAFILE '/home/oracle/orcl/oradata/drew/SDEALLEDITS_DT.dbf'
SIZE 100M AUTOEXTEND ON NEXT 51200K MAXSIZE UNLIMITED EXTENT MANAGEMENT
LOCAL UNIFORM SIZE 320K LOGGING ONLINE SEGMENT SPACE MANAGEMENT MANUAL;
CREATE TABLESPACE SDEALLEDITS_IX DATAFILE '/home/oracle/orcl/oradata/drew/SDEALLEDITS_IX.dbf'
SIZE 100M AUTOEXTEND ON NEXT 51200K MAXSIZE UNLIMITED EXTENT MANAGEMENT
LOCAL UNIFORM SIZE 320K LOGGING ONLINE SEGMENT SPACE MANAGEMENT MANUAL;
CREATE TABLESPACE SDEBUS_DT DATAFILE '/home/oracle/orcl/oradata/drew/SDEBUS_DT.dbf'
SIZE 100M AUTOEXTEND ON NEXT 51200K MAXSIZE UNLIMITED EXTENT MANAGEMENT
LOCAL UNIFORM SIZE 320K LOGGING ONLINE SEGMENT SPACE MANAGEMENT MANUAL;
CREATE TABLESPACE SDEBUS_DT_M DATAFILE '/home/oracle/orcl/oradata/drew/SDEBUS_DT_M.dbf'
SIZE 100M AUTOEXTEND ON NEXT 51200K MAXSIZE UNLIMITED EXTENT MANAGEMENT
LOCAL UNIFORM SIZE 320K LOGGING ONLINE SEGMENT SPACE MANAGEMENT MANUAL;
CREATE TABLESPACE SDEBUS_IX DATAFILE '/home/oracle/orcl/oradata/drew/SDEBUS_IX.dbf'
SIZE 100M AUTOEXTEND ON NEXT 51200K MAXSIZE UNLIMITED EXTENT MANAGEMENT
LOCAL UNIFORM SIZE 320K LOGGING ONLINE SEGMENT SPACE MANAGEMENT MANUAL;
CREATE TABLESPACE SDEBUS_LOB_SEG DATAFILE '/home/oracle/orcl/oradata/drew/SDEBUS_LOB_SEG.dbf'
SIZE 100M AUTOEXTEND ON NEXT 51200K MAXSIZE UNLIMITED EXTENT MANAGEMENT
LOCAL UNIFORM SIZE 320K LOGGING ONLINE SEGMENT SPACE MANAGEMENT MANUAL;
CREATE TABLESPACE SDEBUS_LOB_SEG_IX DATAFILE '/home/oracle/orcl/oradata/drew/SDEBUS_LOB_SEG_IX.dbf'
SIZE 100M AUTOEXTEND ON NEXT 51200K MAXSIZE UNLIMITED EXTENT MANAGEMENT
LOCAL UNIFORM SIZE 320K LOGGING ONLINE SEGMENT SPACE MANAGEMENT MANUAL;
CREATE TABLESPACE SDEDELTA_DT DATAFILE '/home/oracle/orcl/oradata/drew/SDEDELTA_DT.dbf'
SIZE 100M AUTOEXTEND ON NEXT 51200K MAXSIZE UNLIMITED EXTENT MANAGEMENT
LOCAL UNIFORM SIZE 320K LOGGING ONLINE SEGMENT SPACE MANAGEMENT MANUAL;
CREATE TABLESPACE SDEDELTA_DT_M DATAFILE '/home/oracle/orcl/oradata/drew/SDEDELTA_DT_M.dbf'
SIZE 100M AUTOEXTEND ON NEXT 51200K MAXSIZE UNLIMITED EXTENT MANAGEMENT
LOCAL UNIFORM SIZE 320K LOGGING ONLINE SEGMENT SPACE MANAGEMENT MANUAL;
CREATE TABLESPACE SDEDELTA_IX DATAFILE '/home/oracle/orcl/oradata/drew/SDEDELTA_IX.dbf'
SIZE 100M AUTOEXTEND ON NEXT 51200K MAXSIZE UNLIMITED EXTENT MANAGEMENT
LOCAL UNIFORM SIZE 320K LOGGING ONLINE SEGMENT SPACE MANAGEMENT MANUAL;
CREATE TABLESPACE SDEDELTA_LOB_SEG DATAFILE '/home/oracle/orcl/oradata/drew/SDEDELTA_LOB_SEG.dbf'
SIZE 100M AUTOEXTEND ON NEXT 51200K MAXSIZE UNLIMITED EXTENT MANAGEMENT
LOCAL UNIFORM SIZE 320K LOGGING ONLINE SEGMENT SPACE MANAGEMENT MANUAL;
CREATE TABLESPACE SDEDELTA_LOB_SEG_IX DATAFILE '/home/oracle/orcl/oradata/drew/SDEDELTA_LOB_SEG_IX.dbf'
SIZE 100M AUTOEXTEND ON NEXT 51200K MAXSIZE UNLIMITED EXTENT MANAGEMENT
LOCAL UNIFORM SIZE 320K LOGGING ONLINE SEGMENT SPACE MANAGEMENT MANUAL;
CREATE TABLESPACE SDEFEA_DT_M DATAFILE '/home/oracle/orcl/oradata/drew/SDEFEA_DT_M.dbf'
SIZE 100M AUTOEXTEND ON NEXT 51200K MAXSIZE UNLIMITED EXTENT MANAGEMENT
LOCAL UNIFORM SIZE 320K LOGGING ONLINE SEGMENT SPACE MANAGEMENT MANUAL;
CREATE TABLESPACE SDEFEA_IX DATAFILE '/home/oracle/orcl/oradata/drew/SDEFEA_IX.dbf'
SIZE 100M AUTOEXTEND ON NEXT 51200K MAXSIZE UNLIMITED EXTENT MANAGEMENT
LOCAL UNIFORM SIZE 320K LOGGING ONLINE SEGMENT SPACE MANAGEMENT MANUAL;
CREATE TABLESPACE SDEFEA_LOB_SEG DATAFILE '/home/oracle/orcl/oradata/drew/SDEFEA_LOB_SEG.dbf'
SIZE 100M AUTOEXTEND ON NEXT 51200K MAXSIZE UNLIMITED EXTENT MANAGEMENT
LOCAL UNIFORM SIZE 320K LOGGING ONLINE SEGMENT SPACE MANAGEMENT MANUAL;
CREATE TABLESPACE SDEFEA_LOB_SEG_IX DATAFILE '/home/oracle/orcl/oradata/drew/SDEFEA_LOB_SEG_IX.dbf'
SIZE 100M AUTOEXTEND ON NEXT 51200K MAXSIZE UNLIMITED EXTENT MANAGEMENT
LOCAL UNIFORM SIZE 320K LOGGING ONLINE SEGMENT SPACE MANAGEMENT MANUAL;
CREATE TABLESPACE SDENET_BLOB DATAFILE '/home/oracle/orcl/oradata/drew/SDENET_BLOB.dbf'
SIZE 100M AUTOEXTEND ON NEXT 51200K MAXSIZE UNLIMITED EXTENT MANAGEMENT
LOCAL UNIFORM SIZE 320K LOGGING ONLINE SEGMENT SPACE MANAGEMENT MANUAL;
CREATE TABLESPACE SDESPA_DT_M DATAFILE '/home/oracle/orcl/oradata/drew/SDESPA_DT_M.dbf'
SIZE 100M AUTOEXTEND ON NEXT 51200K MAXSIZE UNLIMITED EXTENT MANAGEMENT
LOCAL UNIFORM SIZE 320K LOGGING ONLINE SEGMENT SPACE MANAGEMENT MANUAL;
CREATE TABLESPACE SDESPA_IX DATAFILE '/home/oracle/orcl/oradata/drew/SDESPA_IX.dbf'
SIZE 100M AUTOEXTEND ON NEXT 51200K MAXSIZE UNLIMITED EXTENT MANAGEMENT
LOCAL UNIFORM SIZE 320K LOGGING ONLINE SEGMENT SPACE MANAGEMENT MANUAL;
CREATE TABLESPACE SDETAXREPAIR_DT DATAFILE '/home/oracle/orcl/oradata/drew/SDETAXREPAIR_DT.dbf'
SIZE 100M AUTOEXTEND ON NEXT 51200K MAXSIZE UNLIMITED EXTENT MANAGEMENT
LOCAL UNIFORM SIZE 320K LOGGING ONLINE SEGMENT SPACE MANAGEMENT MANUAL;
CREATE TABLESPACE SDETAXREPAIR_IX DATAFILE '/home/oracle/orcl/oradata/drew/SDETAXREPAIR_IX.dbf'
SIZE 100M AUTOEXTEND ON NEXT 51200K MAXSIZE UNLIMITED EXTENT MANAGEMENT
LOCAL UNIFORM SIZE 320K LOGGING ONLINE SEGMENT SPACE MANAGEMENT MANUAL;
CREATE TABLESPACE SDEUSER_DT DATAFILE '/home/oracle/orcl/oradata/drew/SDEUSER_DT.dbf'
SIZE 100M AUTOEXTEND ON NEXT 51200K MAXSIZE UNLIMITED EXTENT MANAGEMENT
LOCAL UNIFORM SIZE 320K LOGGING ONLINE SEGMENT SPACE MANAGEMENT MANUAL;
CREATE TABLESPACE SDE_DT_M DATAFILE '/home/oracle/orcl/oradata/drew/SDE_DT_M.dbf'
SIZE 100M AUTOEXTEND ON NEXT 51200K MAXSIZE UNLIMITED EXTENT MANAGEMENT
LOCAL UNIFORM SIZE 320K LOGGING ONLINE SEGMENT SPACE MANAGEMENT MANUAL;
CREATE TABLESPACE TIS_DT DATAFILE '/home/oracle/orcl/oradata/drew/TIS_DT.dbf'
SIZE 100M AUTOEXTEND ON NEXT 51200K MAXSIZE UNLIMITED EXTENT MANAGEMENT
LOCAL UNIFORM SIZE 320K LOGGING ONLINE SEGMENT SPACE MANAGEMENT MANUAL;
CREATE TABLESPACE TIS_IX DATAFILE '/home/oracle/orcl/oradata/drew/TIS_IX.dbf'
SIZE 100M AUTOEXTEND ON NEXT 51200K MAXSIZE UNLIMITED EXTENT MANAGEMENT
LOCAL UNIFORM SIZE 320K LOGGING ONLINE SEGMENT SPACE MANAGEMENT MANUAL;
CREATE TABLESPACE TOOLS DATAFILE '/home/oracle/orcl/oradata/drew/TOOLS.dbf'
SIZE 100M AUTOEXTEND ON NEXT 51200K MAXSIZE UNLIMITED EXTENT MANAGEMENT
LOCAL UNIFORM SIZE 320K LOGGING ONLINE SEGMENT SPACE MANAGEMENT MANUAL;
--5. Create the user/schema

create user sde identified by sde default tablespace sde;
create user ALLEDITS identified by alledits default tablespace SDEALLEDITS_DT;
create user DISGISDB identified by disgisdb default tablespace SDEBUS_DT;

--6. Grant all necessary permissions to the new user:

--GRANT DBA TO SDE;

ALLEDITS
DISGISDB
--Alternatively:

grant CREATE SESSION to sde;
grant CREATE TABLE to sde;
grant CREATE TRIGGER to sde;
grant CREATE SEQUENCE to sde;
grant CREATE PROCEDURE to sde;

grant EXECUTE ON DBMS_CRYPTO to sde;
grant CREATE INDEXTYPE to sde;
grant CREATE LIBRARY to sde;
grant CREATE OPERATOR to sde;
grant CREATE PUBLIC SYNONYM to sde;
grant CREATE TYPE to sde;
grant CREATE VIEW to sde;
grant DROP PUBLIC SYNONYM to sde;
grant ADMINISTER DATABASE TRIGGER to sde;

grant ALTER ANY INDEX to sde;
grant ALTER ANY TABLE to sde;
grant CREATE ANY INDEX to sde;
grant CREATE ANY TRIGGER to sde;
grant CREATE ANY VIEW to sde;
grant DROP ANY INDEX to sde;
grant DROP ANY VIEW to sde;
grant SELECT ANY TABLE to sde;

grant ALTER SESSION to sde;
grant ANALYZE ANY to sde;
grant SELECT ANY DICTIONARY to sde;
grant CREATE DATABASE LINK to sde;
grant CREATE MATERIALIZED VIEW to sde;
grant RESTRICTED SESSION to sde;
grant UNLIMITED TABLESPACE to sde;
grant ALTER SYSTEM to sde;
grant SELECT_CATALOG_ROLE to sde;


grant CREATE SESSION to alledits;
grant CREATE TABLE to alledits;
grant CREATE TRIGGER to alledits;
grant CREATE SEQUENCE to alledits;
grant CREATE PROCEDURE to alledits;

grant EXECUTE ON DBMS_CRYPTO to alledits;
grant CREATE INDEXTYPE to alledits;
grant CREATE LIBRARY to alledits;
grant CREATE OPERATOR to alledits;
grant CREATE PUBLIC SYNONYM to alledits;
grant CREATE TYPE to alledits;
grant CREATE VIEW to alledits;
grant DROP PUBLIC SYNONYM to alledits;
grant ADMINISTER DATABASE TRIGGER to alledits;

grant ALTER ANY INDEX to alledits;
grant ALTER ANY TABLE to alledits;
grant CREATE ANY INDEX to alledits;
grant CREATE ANY TRIGGER to alledits;
grant CREATE ANY VIEW to alledits;
grant DROP ANY INDEX to alledits;
grant DROP ANY VIEW to alledits;
grant SELECT ANY TABLE to alledits;

grant ALTER SESSION to alledits;
grant ANALYZE ANY to alledits;
grant SELECT ANY DICTIONARY to alledits;
grant CREATE DATABASE LINK to alledits;
grant CREATE MATERIALIZED VIEW to alledits;
grant RESTRICTED SESSION to alledits;
grant UNLIMITED TABLESPACE to alledits;
grant ALTER SYSTEM to alledits;
grant SELECT_CATALOG_ROLE to alledits;


grant CREATE SESSION to disgisdb;
grant CREATE TABLE to disgisdb;
grant CREATE TRIGGER to disgisdb;
grant CREATE SEQUENCE to disgisdb;
grant CREATE PROCEDURE to disgisdb;

grant EXECUTE ON DBMS_CRYPTO to disgisdb;
grant CREATE INDEXTYPE to disgisdb;
grant CREATE LIBRARY to disgisdb;
grant CREATE OPERATOR to disgisdb;
grant CREATE PUBLIC SYNONYM to disgisdb;
grant CREATE TYPE to disgisdb;
grant CREATE VIEW to disgisdb;
grant DROP PUBLIC SYNONYM to disgisdb;
grant ADMINISTER DATABASE TRIGGER to disgisdb;

grant ALTER ANY INDEX to disgisdb;
grant ALTER ANY TABLE to disgisdb;
grant CREATE ANY INDEX to disgisdb;
grant CREATE ANY TRIGGER to disgisdb;
grant CREATE ANY VIEW to disgisdb;
grant DROP ANY INDEX to disgisdb;
grant DROP ANY VIEW to disgisdb;
grant SELECT ANY TABLE to disgisdb;

grant ALTER SESSION to disgisdb;
grant ANALYZE ANY to disgisdb;
grant SELECT ANY DICTIONARY to disgisdb;
grant CREATE DATABASE LINK to disgisdb;
grant CREATE MATERIALIZED VIEW to disgisdb;
grant RESTRICTED SESSION to disgisdb;
grant UNLIMITED TABLESPACE to disgisdb;
grant ALTER SYSTEM to disgisdb;
grant SELECT_CATALOG_ROLE to disgisdb;

--8. Create a directory for the SYSTEM user to access:

create directory DPUMP1 as '/home/oracle/restores';


--9. Grant R/W to SYSTEM user to read the files in the directory:

GRANT READ, WRITE ON DIRECTORY DPUMP1 to system;


--10. Run the IMPDP from the CMD window:

--impdp system/sys directory=dpump1 logfile=sde_imp.log dumpfile=SDE_SCHEMA.DMP schemas=sde


--11. Log into SQLPlus and check for invalid objects:

Select owner, object_name, object_type from dba_objects where owner='SDE' and status='INVALID';


--12. Compile any invalid schema objects:

Exec dbms_utility.compile_schema(schema => 'SDE');


