CREATE TABLESPACE SDE DATAFILE '{ORACLE_BASE}\oradata\{DB_UNIQUE_NAME}\SDE.dbf' 
SIZE 100M AUTOEXTEND ON NEXT 51200K MAXSIZE UNLIMITED EXTENT MANAGEMENT 
LOCAL UNIFORM SIZE 320K LOGGING ONLINE SEGMENT SPACE MANAGEMENT MANUAL;