create table parcel_polygon_errors as 
SELECT OBJECTID,
  SDO_GEOM.VALIDATE_GEOMETRY(A.SHAPE, SR.XYCLUSTER_TOL) as err,
  SHAPE
FROM PARCEL_POLYGON A,
  (SELECT XYCLUSTER_TOL
  FROM SPATIAL_REFERENCES S
  JOIN LAYERS L
  ON S.SRID          = L.SRID
  WHERE L.TABLE_NAME = 'PARCEL_POLYGON'
  ) SR
WHERE SDO_GEOM.VALIDATE_GEOMETRY(A.SHAPE, SR.XYCLUSTER_TOL) <> 'TRUE';

UPDATE PARCEL_POLYGON_ERRORS A SET SHAPE = 
MDSYS.SDO_UTIL.RECTIFY_GEOMETRY(A.SHAPE,0.016666666666667) 
WHERE SDO_GEOM.VALIDATE_GEOMETRY(A.SHAPE, 0.016666666666667) <> 'TRUE';

sdo_util.rectify_geometry(A.SHAPE,0.016666666666667)