SET SERVEROUTPUT ON
DECLARE
  SX       NUMBER;
  SY       NUMBER;
  EX       NUMBER;
  EY       NUMBER;
  rings    NUMBER;
  CURID    NUMBER;
  ISEMPTY  NUMBER;
  ISCLOSED NUMBER;
  CURSOR rows
  IS
    SELECT OBJECTID,
      SHAPE,
      SDE.ST_NUMGEOMETRIES(SHAPE) AS GEOMS
    FROM SDE_ST
    WHERE SDE.ST_NUMGEOMETRIES(SHAPE) > 1;
BEGIN
  DBMS_OUTPUT.ENABLE (100000000);
  FOR row IN rows
  LOOP
    RINGS := ROW.GEOMS;
    CURID := ROW.OBJECTID;
    FOR I IN 0..RINGS-1 LOOP
    SELECT SDE.ST_ISEMPTY(A.SHAPE) INTO ISEMPTY FROM (SELECT SDE.ST_INTERIORRINGN(ROW.SHAPE, I) AS SHAPE FROM DUAL) A;
    SELECT SDE.ST_ISCLOSED(A.SHAPE) INTO ISCLOSED FROM (SELECT SDE.ST_INTERIORRINGN(ROW.SHAPE, I) AS SHAPE FROM DUAL) A;
    SELECT SDE.ST_X(SDE.ST_STARTPOINT(A.SHAPE)), SDE.ST_Y(SDE.ST_STARTPOINT(A.SHAPE)), SDE.ST_X(SDE.ST_ENDPOINT(A.SHAPE)), SDE.ST_Y(SDE.ST_ENDPOINT(A.SHAPE))
    INTO SX, SY, EX, EY 
    FROM (SELECT SDE.ST_INTERIORRINGN(ROW.SHAPE, I) AS SHAPE FROM DUAL) A;
    DBMS_OUTPUT.PUT_LINE(ROW.OBJECTID || ',' || I || ',' || ISEMPTY || ',' || ISCLOSED || ',' || SX || ','|| SY || ','|| EX || ','|| EY);
    END LOOP;
END LOOP;
END;
/