CREATE TABLE ORANGE_MARKETS
  (
    MARKET_ID NUMBER (38) NOT NULL,
    MARKET_NAME VARCHAR2 (32),
    SHAPE MDSYS.SDO_GEOMETRY
  );
  
INSERT
INTO ORANGE_MARKETS VALUES
  (
    1,
    'ORANGE_POLY',
    MDSYS.SDO_GEOMETRY( 2003, 8307, NULL, MDSYS.SDO_ELEM_INFO_ARRAY(1,1003,3), MDSYS.SDO_ORDINATE_ARRAY(1,1, 5,7) )
  );
  
INSERT
INTO ORANGE_MARKETS VALUES
  (
    2,
    'ORANGE_PT',
    MDSYS.SDO_GEOMETRY( 2001, 8307, MDSYS.SDO_POINT_TYPE(12, 14, NULL), NULL, NULL)
  );
  
INSERT
INTO MDSYS.USER_SDO_GEOM_METADATA VALUES
  (
    'ORANGE_MARKETS',
    'SHAPE',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 0, 20,0.005), MDSYS.SDO_DIM_ELEMENT('Y', 0, 20, 0.005)),
    8307
  );
  
CREATE INDEX ORANGE_SPATIAL_IDX ON ORANGE_MARKETS
  (
    SHAPE
  )
  INDEXTYPE IS MDSYS.SPATIAL_INDEX;
  

DROP TABLE ORANGE_MARKETS;
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'ORANGE_MARKETS';
COMMIT;

select * from orange_markets where market_name = 'ORANGE_POLY'

INSERT
INTO USER_SDO_GEOM_METADATA VALUES
  (
    'polygon_z',
    'shape',
    MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X', 0, 20, 0.005), MDSYS.SDO_DIM_ELEMENT('Y', 0, 20, 0.005), MDSYS.SDO_DIM_ELEMENT('Z', -100, 100, 0.005) ),
    NULL -- SRID
  );
